spring.application.name=sandboxpro
server.port=8080

spring.data.mongodb.uri=mongodb+srv://user:userpass@cluster0.gcqzyeh.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=notesdb

gemini.api.key=AIzaSyCXscGoM1inf0B-KS7BBRxuoyJCvaV_XeA
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent

jwt.secret=MyAnatomyWorkshopSuperSecretKeyFor256BitHmacSha2026!
jwt.expiration-ms=86400000

logging.level.com.myanatomy=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
